language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"

dist: trusty

addons:
  chrome: beta

cache: yarn

script:
  - yarn lint
  - yarn build
  - yarn test

after_success:
  - yarn coverage
