environment:
  matrix:
    - nodejs_version: "Stable"
    - nodejs_version: "LTS"

cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

before_build:
  - yarn lint

build_script:
  - yarn build

test_script:
  - yarn test

on_success:
  - yarn coverage

build: off
